/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.Koneksi;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamelia
 */
public class MenuView extends javax.swing.JFrame {

  /**
   * Creates new form MenuView
   */
  public MenuView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktop = new javax.swing.JDesktopPane();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    itemBarang = new javax.swing.JMenuItem();
    itemPelanggan = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    itemTransaksi = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
    desktop.setLayout(desktopLayout);
    desktopLayout.setHorizontalGroup(
        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE));
    desktopLayout.setVerticalGroup(
        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE));

    jMenu1.setText("Menu");

    itemBarang.setText("Barang");
    itemBarang.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemBarangActionPerformed(evt);
      }
    });
    jMenu1.add(itemBarang);

    itemPelanggan.setText("Pelanggan");
    itemPelanggan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemPelangganActionPerformed(evt);
      }
    });
    jMenu1.add(itemPelanggan);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Transaksi");

    itemTransaksi.setText("Penjualan");
    itemTransaksi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemTransaksiActionPerformed(evt);
      }
    });
    jMenu2.add(itemTransaksi);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_itemBarangActionPerformed
    BarangView barang = new BarangView();
    barang.setVisible(true);
    desktop.add(barang);
    try {
      barang.setSelected(true);
    } catch (Exception e) {
      Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, e);
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }// GEN-LAST:event_itemBarangActionPerformed

  private void itemPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_itemPelangganActionPerformed
    PelangganView pelanggan = new PelangganView();
    pelanggan.setVisible(true);
    desktop.add(pelanggan);
    try {
      pelanggan.setSelected(true);
    } catch (Exception e) {
      Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, e);
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }// GEN-LAST:event_itemPelangganActionPerformed

  private void itemTransaksiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_itemTransaksiActionPerformed
    PenjualanView penjualan = new PenjualanView();
    penjualan.setVisible(true);
    desktop.add(penjualan);
    try {
      penjualan.setSelected(true);
    } catch (Exception e) {
      Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, e);
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }// GEN-LAST:event_itemTransaksiActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MenuView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktop;
  private javax.swing.JMenuItem itemBarang;
  private javax.swing.JMenuItem itemPelanggan;
  private javax.swing.JMenuItem itemTransaksi;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  // End of variables declaration//GEN-END:variables
}
